.TH "STX CONFIG SHOW" "1" "2026-04-19" "0.1.0" "stx config show Manual"
.SH NAME
stx\-config\-show \- Print merged, validated config as YAML.
.SH SYNOPSIS
.B stx config show
[OPTIONS]
.SH DESCRIPTION
Print merged, validated config as YAML.
.SH OPTIONS
.TP
\fB\-c,\fP \-\-config FILE
Experiment YAML.  [default: (configs/default.yaml or $STX_CONFIG)]
