.TH "STX CONFIG DIFF" "1" "2026-04-19" "0.1.0" "stx config diff Manual"
.SH NAME
stx\-config\-diff \- Print keys that differ from Pydantic...
.SH SYNOPSIS
.B stx config diff
[OPTIONS]
.SH DESCRIPTION
Print keys that differ from Pydantic defaults for this experiment mode.
.SH OPTIONS
.TP
\fB\-c,\fP \-\-config FILE
Experiment YAML.  [default: (configs/default.yaml or $STX_CONFIG)]
